const PRICE=235000, KG=25, MIN=2, WA="989044575134";
const fa=n=>new Intl.NumberFormat("fa-IR").format(n);
function calc(){let a=[...document.querySelectorAll(".q")].map(x=>({size:x.dataset.size,qty:Math.max(0,parseInt(x.value||0))}));let count=a.reduce((s,x)=>s+x.qty,0), total=count*KG*PRICE;document.querySelector("#count").textContent=fa(count)+" گونی";document.querySelector("#weight").textContent=fa(count*KG)+" کیلو";document.querySelector("#total").textContent=fa(total)+" تومان";document.querySelector("#error").style.display=count<MIN?"block":"none";return{a,count,total}}
document.querySelectorAll(".q").forEach(x=>x.addEventListener("input",calc));calc();
document.querySelectorAll(".size-buttons button").forEach(b=>b.addEventListener("click",()=>{let x=document.querySelector(`.q[data-size="${b.dataset.size}"]`);x.value=Math.max(1,parseInt(x.value||0));calc();document.querySelector("#order").scrollIntoView({behavior:"smooth"});}));
document.querySelector("#form").addEventListener("submit",e=>{e.preventDefault();let r=calc();if(!document.querySelector("#phone").checkValidity()||!document.querySelector("#postal").checkValidity()){alert("لطفاً شماره موبایل ۱۱ رقمی و کد پستی ۱۰ رقمی را صحیح وارد کنید.");return}if(r.count<MIN){alert("حداقل سفارش ۲ گونی است.");return}let items=r.a.filter(x=>x.qty>0).map(x=>`📏 ${x.size}: ${fa(x.qty)} گونی`).join("\n");let msg=`سلام نئو پلاست 👋\nسفارش جدید:\n\n👤 نام: ${document.querySelector("#name").value}\n📞 موبایل: ${document.querySelector("#phone").value}\n🏠 آدرس تحویل: ${document.querySelector("#address").value}\n📮 کد پستی: ${document.querySelector("#postal").value}\n\n📦 جزئیات سفارش:\n${items}\n\n📦 تعداد کل: ${fa(r.count)} گونی\n⚖️ وزن کل: ${fa(r.count*KG)} کیلو\n💵 مبلغ کل: ${fa(r.total)} تومان\n💳 روش پرداخت: کارت به کارت\n🔎 شماره پیگیری: ${document.querySelector("#tracking").value||"وارد نشده"}\n\n📍 آدرس کارخانه: آذربایجان غربی - ارومیه - امامزاده - روستای بیرلان`;window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank")});
document.querySelectorAll(".copy").forEach(b=>b.addEventListener("click",async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);document.querySelector("#toast").classList.add("show");setTimeout(()=>document.querySelector("#toast").classList.remove("show"),1200)}catch(e){alert("کپی انجام نشد")}}));
document.querySelector("#menu").addEventListener("click",()=>document.querySelector("#nav").classList.toggle("open"));
document.querySelectorAll("#nav a").forEach(a=>a.addEventListener("click",()=>document.querySelector("#nav").classList.remove("open")));
